import Navbar from "@/components/navbar/page";
import "./globals.css";
import Footer from "@/components/footer/page";


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`  flex flex-col justify-between`}>
        <Navbar/>
        <main className=" pt-6">
          {children}
        </main>
        <Footer/>
      </body>
    </html>
  );
}
